"""
TTS Microservice — Kokoro (English) + Edge-TTS (multilingual).

Runs as a standalone FastAPI service on port 8002.
Accepts text and returns synthesized audio (WAV).

Routing logic:
  - English (lang=en or unset): Kokoro-82M (local, fast, high quality)
  - Any other language:         Edge-TTS (Microsoft, free, internet required)
"""

import io
import os
import time
import logging
import asyncio

import soundfile as sf
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import Response
from pydantic import BaseModel

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)

app = FastAPI(
    title="TTS Service",
    description="Text-to-Speech: Kokoro (English) + Edge-TTS (multilingual)",
    version="2.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Configuration ────────────────────────────────────────────────────
TTS_VOICE = os.getenv("TTS_VOICE", "af_sky")
TTS_LANG_CODE = os.getenv("TTS_LANG_CODE", "a")  # 'a' = American English

# Edge-TTS voice map: ISO 639-1 language code → Edge-TTS voice name
# Add more languages here as needed
EDGE_TTS_VOICE_MAP: dict[str, str] = {
    "en": "en-US-JennyNeural",       # English (fallback when Kokoro unavailable)
    "ur": "ur-PK-UzmaNeural",       # Urdu (Pakistani)
    "ar": "ar-SA-ZariyahNeural",     # Arabic
    "hi": "hi-IN-SwaraNeural",       # Hindi
    "fr": "fr-FR-DeniseNeural",      # French
    "de": "de-DE-KatjaNeural",       # German
    "es": "es-ES-ElviraNeural",      # Spanish
    "zh": "zh-CN-XiaoxiaoNeural",    # Chinese (Mandarin)
    "ja": "ja-JP-NanamiNeural",      # Japanese
    "ko": "ko-KR-SunHiNeural",       # Korean
    "pt": "pt-BR-FranciscaNeural",   # Portuguese (Brazilian)
    "ru": "ru-RU-SvetlanaNeural",    # Russian
    "tr": "tr-TR-EmelNeural",        # Turkish
    "it": "it-IT-ElsaNeural",        # Italian
    "nl": "nl-NL-ColetteNeural",     # Dutch
    "pl": "pl-PL-ZofiaNeural",       # Polish
    "sv": "sv-SE-SofieNeural",       # Swedish
    "da": "da-DK-ChristelNeural",    # Danish
    "fi": "fi-FI-NooraNeural",       # Finnish
    "nb": "nb-NO-PernilleNeural",    # Norwegian
    "id": "id-ID-GadisNeural",       # Indonesian
    "ms": "ms-MY-YasminNeural",      # Malay
    "th": "th-TH-PremwadeeNeural",   # Thai
    "vi": "vi-VN-HoaiMyNeural",      # Vietnamese
    "fa": "fa-IR-DilaraNeural",      # Persian/Farsi
    "bn": "bn-BD-NabanitaNeural",    # Bengali
    "pa": "pa-IN-OjasNeural",        # Punjabi
    "ta": "ta-IN-PallaviNeural",     # Tamil
    "te": "te-IN-MohanNeural",       # Telugu
}

# Global Kokoro state
_pipeline = None
_kokoro_voice_ready = False  # True only after the voice file is confirmed cached

_last_inference_at: float = 0.0   # updated by real requests AND keepalive
_KEEPALIVE_IDLE_SEC: float = 8 * 60   # run keepalive when idle > 8 min
_KEEPALIVE_CHECK_SEC: float = 60      # poll every 60 s


def get_pipeline():
    """Load the Kokoro TTS pipeline (model weights only, no voice files)."""
    global _pipeline
    if _pipeline is None:
        from kokoro import KPipeline
        logger.info(f"Loading Kokoro TTS pipeline (lang={TTS_LANG_CODE})...")
        _pipeline = KPipeline(lang_code=TTS_LANG_CODE)
        logger.info("Kokoro TTS pipeline loaded successfully.")
    return _pipeline


# ── Request Models ───────────────────────────────────────────────────

class SynthesizeRequest(BaseModel):
    text: str
    voice: str = TTS_VOICE
    language: str = "en"   # ISO 639-1 language code from STT detection


# ── Synthesis Helpers ────────────────────────────────────────────────

def _kokoro_synthesize(text: str, voice: str) -> bytes:
    """Synthesize using local Kokoro model (English only). Raises on failure."""
    pipeline = get_pipeline()
    audio_chunks = []

    for _, _, audio in pipeline(text, voice=voice):
        if audio is not None:
            audio_chunks.append(audio)

    if not audio_chunks:
        raise ValueError("No audio generated by Kokoro.")

    import numpy as np
    full_audio = np.concatenate(audio_chunks)

    wav_buffer = io.BytesIO()
    sf.write(wav_buffer, full_audio, 24000, format="WAV", subtype="PCM_16")
    return wav_buffer.getvalue()


def _try_warm_kokoro_voice() -> bool:
    """
    Attempt to synthesize a short test string to force the voice file to be
    downloaded and cached. Returns True on success, False on failure.
    Called at startup so the first real request is fast and offline-safe.
    """
    global _kokoro_voice_ready
    try:
        _kokoro_synthesize("Hello.", TTS_VOICE)
        _kokoro_voice_ready = True
        # Lock HuggingFace Hub to offline mode so it never tries to re-fetch
        os.environ["HF_HUB_OFFLINE"] = "1"
        logger.info(f"Kokoro voice '{TTS_VOICE}' cached and ready (offline mode enabled).")
        return True
    except Exception as e:
        _kokoro_voice_ready = False
        logger.warning(
            f"Kokoro voice pre-warm failed (will use Edge-TTS for English as fallback): {e}"
        )
        return False


def _pyttsx3_synthesize(text: str) -> bytes:
    """
    Offline fallback: Windows SAPI (pyttsx3). No internet required.
    Works on any Windows machine with built-in voices (e.g. Microsoft David/Zira).
    Saves to a temp WAV file then returns the bytes.
    """
    import pyttsx3
    import tempfile

    engine = pyttsx3.init()
    engine.setProperty("rate", 175)   # slightly slower than default (200)
    engine.setProperty("volume", 1.0)

    tmp_path = None
    try:
        with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as f:
            tmp_path = f.name
        engine.save_to_file(text, tmp_path)
        engine.runAndWait()
        with open(tmp_path, "rb") as f:
            return f.read()
    finally:
        engine.stop()
        if tmp_path:
            try:
                os.unlink(tmp_path)
            except OSError:
                pass


async def _edge_tts_synthesize(text: str, language: str) -> bytes:
    """Synthesize using Edge-TTS (Microsoft) for multilingual support."""
    import edge_tts

    voice = EDGE_TTS_VOICE_MAP.get(language)
    if not voice:
        # Try base language code (e.g. "zh-CN" → "zh")
        base = language.split("-")[0]
        voice = EDGE_TTS_VOICE_MAP.get(base)

    if not voice:
        logger.warning(
            f"No Edge-TTS voice found for language '{language}'. "
            "Falling back to en-US-JennyNeural."
        )
        voice = "en-US-JennyNeural"

    logger.info(f"[Edge-TTS] Synthesizing '{text[:60]}...' with voice={voice}")

    communicate = edge_tts.Communicate(text, voice)
    mp3_chunks: list[bytes] = []

    async for chunk in communicate.stream():
        if chunk["type"] == "audio":
            mp3_chunks.append(chunk["data"])

    if not mp3_chunks:
        raise ValueError("Edge-TTS returned no audio chunks.")

    # Convert MP3 → WAV using soundfile + numpy via io
    import numpy as np
    mp3_bytes = b"".join(mp3_chunks)

    # soundfile can read MP3 if libsndfile supports it; fall back to pydub if not
    try:
        audio_data, sample_rate = sf.read(io.BytesIO(mp3_bytes), dtype="int16")
    except Exception:
        # pydub fallback (requires ffmpeg)
        try:
            from pydub import AudioSegment
            segment = AudioSegment.from_file(io.BytesIO(mp3_bytes), format="mp3")
            wav_buf = io.BytesIO()
            segment.export(wav_buf, format="wav")
            return wav_buf.getvalue()
        except Exception as e2:
            raise RuntimeError(f"Could not decode Edge-TTS audio: {e2}") from e2

    wav_buffer = io.BytesIO()
    sf.write(wav_buffer, audio_data, sample_rate, format="WAV", subtype="PCM_16")
    return wav_buffer.getvalue()


# ── Startup & Health ─────────────────────────────────────────────────

async def _keepalive_loop():
    """
    Background loop that re-synthesizes a short string whenever Kokoro has been
    idle for _KEEPALIVE_IDLE_SEC.  Keeps the model loaded and ONNX/GPU context
    alive so the next real request starts instantly.
    """
    global _last_inference_at
    while True:
        await asyncio.sleep(_KEEPALIVE_CHECK_SEC)
        if not _kokoro_voice_ready:
            continue
        idle = time.time() - _last_inference_at
        if idle >= _KEEPALIVE_IDLE_SEC:
            logger.info(
                f"[TTS] Keep-alive triggered (idle {idle / 60:.1f} min) — running warmup synthesis."
            )
            try:
                await asyncio.to_thread(_kokoro_synthesize, "Ready.", TTS_VOICE)
                _last_inference_at = time.time()
                logger.info("[TTS] Keep-alive synthesis done.")
            except Exception as e:
                logger.warning(f"[TTS] Keep-alive failed: {e}")


@app.on_event("startup")
async def startup_warmup():
    async def _warm():
        global _last_inference_at
        try:
            # Step 1: load the model weights
            await asyncio.to_thread(get_pipeline)
            # Step 2: force voice file download/cache with a test synthesis
            await asyncio.to_thread(_try_warm_kokoro_voice)
            # _try_warm_kokoro_voice already runs a full synthesis pass,
            # which warms up all kernels.  Stamp the inference clock so the
            # keepalive doesn't immediately re-fire after startup.
            _last_inference_at = time.time()
        except Exception as e:
            logger.error(f"TTS warmup failed: {e}")

    asyncio.create_task(_warm())
    asyncio.create_task(_keepalive_loop())


@app.get("/health")
async def health():
    return {
        "status": "healthy",
        "service": "tts",
        "kokoro_voice": TTS_VOICE,
        "kokoro_model_ready": _pipeline is not None,
        "kokoro_voice_ready": _kokoro_voice_ready,
        "english_engine": "kokoro" if _kokoro_voice_ready else "edge-tts-fallback",
        "multilingual": True,
        "supported_languages": list(EDGE_TTS_VOICE_MAP.keys()),
    }


# ── Endpoints ────────────────────────────────────────────────────────

@app.post("/synthesize")
async def synthesize(request: SynthesizeRequest):
    """
    Synthesize text to speech.

    - English (language="en"): uses local Kokoro model (fast, offline)
    - Other languages:         uses Edge-TTS (Microsoft, requires internet)

    Returns: WAV audio bytes.
    """
    if not request.text.strip():
        raise HTTPException(status_code=400, detail="Text cannot be empty.")

    if len(request.text) > 5000:
        raise HTTPException(status_code=400, detail="Text too long. Maximum 5000 characters.")

    global _last_inference_at
    _last_inference_at = time.time()
    start_time = _last_inference_at
    lang = (request.language or "en").lower().split("-")[0]  # normalize "en-US" → "en"

    wav_bytes: bytes | None = None
    engine = "unknown"

    # ── Level 1: Kokoro (English only, offline, best quality) ──────────
    if lang == "en" and _kokoro_voice_ready:
        try:
            wav_bytes = await asyncio.to_thread(_kokoro_synthesize, request.text, request.voice)
            engine = "kokoro"
        except Exception as e:
            logger.warning(f"Kokoro failed: {e}")

    # ── Level 2: Edge-TTS (multilingual, internet required) ────────────
    if wav_bytes is None:
        try:
            wav_bytes = await _edge_tts_synthesize(request.text, lang)
            engine = "edge-tts"
        except Exception as e:
            logger.warning(f"Edge-TTS failed (lang={lang}): {e}")

    # ── Level 3: pyttsx3 (Windows SAPI, fully offline, English only) ──
    if wav_bytes is None:
        try:
            wav_bytes = await asyncio.to_thread(_pyttsx3_synthesize, request.text)
            engine = "pyttsx3"
            logger.info("Using pyttsx3 (Windows SAPI) as offline fallback.")
        except Exception as e:
            logger.error(f"pyttsx3 also failed: {e}")

    if wav_bytes is None:
        logger.error(f"All TTS engines failed for lang={lang}")
        raise HTTPException(status_code=503, detail="All TTS engines unavailable. Check network and service logs.")

    duration = time.time() - start_time
    logger.info(
        f"[{engine}] Synthesized {len(request.text)} chars in {duration:.2f}s "
        f"| language={lang}"
    )

    return Response(
        content=wav_bytes,
        media_type="audio/wav",
        headers={
            "X-Engine": engine,
            "X-Language": lang,
            "X-Processing-Time": str(round(duration, 2)),
        },
    )


@app.post("/synthesize/stream")
async def synthesize_stream(request: SynthesizeRequest):
    """
    Streaming synthesis for English (Kokoro only).
    Non-English falls back to non-streaming /synthesize endpoint.
    """
    if not request.text.strip():
        raise HTTPException(status_code=400, detail="Text cannot be empty.")

    lang = (request.language or "en").lower().split("-")[0]

    if lang != "en":
        # Delegate to non-streaming endpoint for multilingual
        return await synthesize(request)

    try:
        from fastapi.responses import StreamingResponse

        pipeline = get_pipeline()
        sample_rate = 24000

        async def audio_generator():
            for _, _, audio in pipeline(request.text, voice=request.voice):
                if audio is not None:
                    chunk_buffer = io.BytesIO()
                    sf.write(chunk_buffer, audio, sample_rate, format="WAV", subtype="PCM_16")
                    yield chunk_buffer.getvalue()

        return StreamingResponse(audio_generator(), media_type="audio/wav")

    except Exception as e:
        logger.error(f"Streaming synthesis error: {e}")
        raise HTTPException(status_code=500, detail=f"Streaming synthesis failed: {str(e)}")


if __name__ == "__main__":
    import uvicorn

    port = int(os.getenv("TTS_PORT", "8002"))
    uvicorn.run("main:app", host="0.0.0.0", port=port, reload=True)
